# Generated by Django 4.0 on 2021-12-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('hotel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('food', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('other', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=3, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='textEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('invoice_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dropoff_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dropoff', to='Job.location')),
                ('expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Job.expenses')),
                ('pickup_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pickup', to='Job.location')),
                ('start_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='start', to='Job.location')),
            ],
        ),
    ]
