# Generated by Django 4.0 on 2021-12-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('hotel', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('food', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('other', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=3, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tafs',
            fields=[
                ('invoice_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reserves', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('debtor', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(blank=True, max_length=40, null=True)),
                ('rpm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('dropoff_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dropoff', to='Job.location')),
                ('expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Job.expenses')),
                ('pickup_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pickup', to='Job.location')),
                ('start_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='start', to='Job.location')),
                ('taf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.tafs')),
            ],
        ),
    ]
